services:
  app-backend:
    build: ./backend
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}

  app-frontend:
    build: ./frontend
    ports:
      - ${FRONTEND_PORT}:80
    depends_on:
      - "app-backend"